// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'742d9a96bdcd545002b88c06ea674238fba33ca7350e7b900a227042e2f5a62f'>;
export type ExecutionHash =
  ExecutionHashBase<'a414209e5603252a0a9db7c984a033cb6859b740e22e74c4bbb7673ff67994fc'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Agendamento: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly servicoId: CodecTypes['pg/uuid@1']['output'];
      readonly data: CodecTypes['pg/date-temporal@1']['output'];
      readonly horaInicio: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly horaFim: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly status: 'CONFIRMADO' | 'CANCELADO' | 'CONCLUIDO';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Avaliacao: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly agendamentoId: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly nota: CodecTypes['pg/int4@1']['output'];
      readonly comentario: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly BarbeiroEspecialidade: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly especialidadeId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Disponibilidade: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly diaSemana: CodecTypes['pg/int4@1']['output'];
      readonly horaInicio: CodecTypes['pg/text@1']['output'];
      readonly horaFim: CodecTypes['pg/text@1']['output'];
    };
    readonly Especialidade: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly Favorito: {
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly FilaDeEspera: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly dataDesejada: CodecTypes['pg/date-temporal@1']['output'];
      readonly status: 'AGUARDANDO' | 'NOTIFICADO' | 'CONFIRMADO' | 'EXPIRADO';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Servico: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly duracaoMin: CodecTypes['pg/int4@1']['output'];
      readonly preco: Numeric<10, 2>;
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly senhaHash: CodecTypes['pg/text@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly role: 'CLIENTE' | 'BARBEIRO' | 'ADMINISTRADOR';
      readonly pontosFidelidade: CodecTypes['pg/int4@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Agendamento: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly servicoId: CodecTypes['pg/uuid@1']['input'];
      readonly data: CodecTypes['pg/date-temporal@1']['input'];
      readonly horaInicio: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly horaFim: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly status: 'CONFIRMADO' | 'CANCELADO' | 'CONCLUIDO';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Avaliacao: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly agendamentoId: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly nota: CodecTypes['pg/int4@1']['input'];
      readonly comentario: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly BarbeiroEspecialidade: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly especialidadeId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Disponibilidade: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly diaSemana: CodecTypes['pg/int4@1']['input'];
      readonly horaInicio: CodecTypes['pg/text@1']['input'];
      readonly horaFim: CodecTypes['pg/text@1']['input'];
    };
    readonly Especialidade: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly Favorito: {
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly FilaDeEspera: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly dataDesejada: CodecTypes['pg/date-temporal@1']['input'];
      readonly status: 'AGUARDANDO' | 'NOTIFICADO' | 'CONFIRMADO' | 'EXPIRADO';
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Servico: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly duracaoMin: CodecTypes['pg/int4@1']['input'];
      readonly preco: CodecTypes['pg/numeric@1']['input'];
    };
    readonly Usuario: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly senhaHash: CodecTypes['pg/text@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly role: 'CLIENTE' | 'BARBEIRO' | 'ADMINISTRADOR';
      readonly pontosFidelidade: CodecTypes['pg/int4@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly agendamentos: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly data: CodecTypes['pg/date-temporal@1']['output'];
      readonly horaFim: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly horaInicio: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly servicoId: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'CONFIRMADO' | 'CANCELADO' | 'CONCLUIDO';
    };
    readonly avaliacoes: {
      readonly agendamentoId: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly comentario: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nota: CodecTypes['pg/int4@1']['output'];
    };
    readonly barbeiro_especialidades: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly especialidadeId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly disponibilidades: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly diaSemana: CodecTypes['pg/int4@1']['output'];
      readonly horaFim: CodecTypes['pg/text@1']['output'];
      readonly horaInicio: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly especialidades: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
    };
    readonly favoritos: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly fila_de_espera: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['output'];
      readonly clienteId: CodecTypes['pg/uuid@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly dataDesejada: CodecTypes['pg/date-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'AGUARDANDO' | 'NOTIFICADO' | 'CONFIRMADO' | 'EXPIRADO';
    };
    readonly servicos: {
      readonly descricao: CodecTypes['pg/text@1']['output'] | null;
      readonly duracaoMin: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly preco: Numeric<10, 2>;
    };
    readonly usuarios: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly pontosFidelidade: CodecTypes['pg/int4@1']['output'];
      readonly role: 'CLIENTE' | 'BARBEIRO' | 'ADMINISTRADOR';
      readonly senhaHash: CodecTypes['pg/text@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly agendamentos: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly data: CodecTypes['pg/date-temporal@1']['input'];
      readonly horaFim: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly horaInicio: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly servicoId: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'CONFIRMADO' | 'CANCELADO' | 'CONCLUIDO';
    };
    readonly avaliacoes: {
      readonly agendamentoId: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly comentario: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nota: CodecTypes['pg/int4@1']['input'];
    };
    readonly barbeiro_especialidades: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly especialidadeId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly disponibilidades: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly diaSemana: CodecTypes['pg/int4@1']['input'];
      readonly horaFim: CodecTypes['pg/text@1']['input'];
      readonly horaInicio: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly especialidades: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
    };
    readonly favoritos: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly fila_de_espera: {
      readonly barbeiroId: CodecTypes['pg/uuid@1']['input'];
      readonly clienteId: CodecTypes['pg/uuid@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly dataDesejada: CodecTypes['pg/date-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'AGUARDANDO' | 'NOTIFICADO' | 'CONFIRMADO' | 'EXPIRADO';
    };
    readonly servicos: {
      readonly descricao: CodecTypes['pg/text@1']['input'] | null;
      readonly duracaoMin: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly preco: CodecTypes['pg/numeric@1']['input'];
    };
    readonly usuarios: {
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly pontosFidelidade: CodecTypes['pg/int4@1']['input'];
      readonly role: 'CLIENTE' | 'BARBEIRO' | 'ADMINISTRADOR';
      readonly senhaHash: CodecTypes['pg/text@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_Usuario = {
    id: CodecTypes['pg/uuid@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    senhaHash: CodecTypes['pg/text@1']['output'];
    telefone: CodecTypes['pg/text@1']['output'] | null;
    role: 'CLIENTE' | 'BARBEIRO' | 'ADMINISTRADOR';
    pontosFidelidade: CodecTypes['pg/int4@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    agendamentosComoBarbeiro: public_Agendamento[];
    agendamentosComoCliente: public_Agendamento[];
    avaliacoes: public_Avaliacao[];
    disponibilidades: public_Disponibilidade[];
    especialidades: public_BarbeiroEspecialidade[];
    favoritos: public_Favorito[];
    filaDeEspera: public_FilaDeEspera[];
    readonly [RelationKeys]?:
      | 'agendamentosComoBarbeiro'
      | 'agendamentosComoCliente'
      | 'avaliacoes'
      | 'disponibilidades'
      | 'especialidades'
      | 'favoritos'
      | 'filaDeEspera';
  };
  export type public_Servico = {
    id: CodecTypes['pg/uuid@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    descricao: CodecTypes['pg/text@1']['output'] | null;
    duracaoMin: CodecTypes['pg/int4@1']['output'];
    preco: Numeric<10, 2>;
    agendamentos: public_Agendamento[];
    readonly [RelationKeys]?: 'agendamentos';
  };
  export type public_Especialidade = {
    id: CodecTypes['pg/uuid@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    barbeiros: public_BarbeiroEspecialidade[];
    readonly [RelationKeys]?: 'barbeiros';
  };
  export type public_BarbeiroEspecialidade = {
    barbeiroId: CodecTypes['pg/uuid@1']['output'];
    especialidadeId: CodecTypes['pg/uuid@1']['output'];
    barbeiro: public_Usuario;
    especialidade: public_Especialidade;
    readonly [RelationKeys]?: 'barbeiro' | 'especialidade';
  };
  export type public_Disponibilidade = {
    id: CodecTypes['pg/uuid@1']['output'];
    barbeiroId: CodecTypes['pg/uuid@1']['output'];
    diaSemana: CodecTypes['pg/int4@1']['output'];
    horaInicio: CodecTypes['pg/text@1']['output'];
    horaFim: CodecTypes['pg/text@1']['output'];
    barbeiro: public_Usuario;
    readonly [RelationKeys]?: 'barbeiro';
  };
  export type public_Agendamento = {
    id: CodecTypes['pg/uuid@1']['output'];
    clienteId: CodecTypes['pg/uuid@1']['output'];
    barbeiroId: CodecTypes['pg/uuid@1']['output'];
    servicoId: CodecTypes['pg/uuid@1']['output'];
    data: CodecTypes['pg/date-temporal@1']['output'];
    horaInicio: CodecTypes['pg/timestamptz-temporal@1']['output'];
    horaFim: CodecTypes['pg/timestamptz-temporal@1']['output'];
    status: 'CONFIRMADO' | 'CANCELADO' | 'CONCLUIDO';
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    avaliacao: public_Avaliacao | null;
    barbeiro: public_Usuario;
    cliente: public_Usuario;
    servico: public_Servico;
    readonly [RelationKeys]?: 'avaliacao' | 'barbeiro' | 'cliente' | 'servico';
  };
  export type public_FilaDeEspera = {
    id: CodecTypes['pg/uuid@1']['output'];
    clienteId: CodecTypes['pg/uuid@1']['output'];
    barbeiroId: CodecTypes['pg/uuid@1']['output'];
    dataDesejada: CodecTypes['pg/date-temporal@1']['output'];
    status: 'AGUARDANDO' | 'NOTIFICADO' | 'CONFIRMADO' | 'EXPIRADO';
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    cliente: public_Usuario;
    readonly [RelationKeys]?: 'cliente';
  };
  export type public_Avaliacao = {
    id: CodecTypes['pg/uuid@1']['output'];
    agendamentoId: CodecTypes['pg/uuid@1']['output'];
    clienteId: CodecTypes['pg/uuid@1']['output'];
    nota: CodecTypes['pg/int4@1']['output'];
    comentario: CodecTypes['pg/text@1']['output'] | null;
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    agendamento: public_Agendamento;
    cliente: public_Usuario;
    readonly [RelationKeys]?: 'agendamento' | 'cliente';
  };
  export type public_Favorito = {
    clienteId: CodecTypes['pg/uuid@1']['output'];
    barbeiroId: CodecTypes['pg/uuid@1']['output'];
    cliente: public_Usuario;
    readonly [RelationKeys]?: 'cliente';
  };
}

export declare const models: {
  public: {
    Usuario: Models.public_Usuario;
    Servico: Models.public_Servico;
    Especialidade: Models.public_Especialidade;
    BarbeiroEspecialidade: Models.public_BarbeiroEspecialidade;
    Disponibilidade: Models.public_Disponibilidade;
    Agendamento: Models.public_Agendamento;
    FilaDeEspera: Models.public_FilaDeEspera;
    Avaliacao: Models.public_Avaliacao;
    Favorito: Models.public_Favorito;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly agendamentos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly clienteId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly barbeiroId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly servicoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly data: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly horaInicio: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly horaFim: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'CONFIRMADO'>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'agendamentos_clienteId_idx_7ae16308';
                  readonly prefix: 'agendamentos_clienteId_idx';
                  readonly columns: readonly ['clienteId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'agendamentos_barbeiroId_idx_9d9c2279';
                  readonly prefix: 'agendamentos_barbeiroId_idx';
                  readonly columns: readonly ['barbeiroId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'agendamentos_servicoId_idx_49e97e5d';
                  readonly prefix: 'agendamentos_servicoId_idx';
                  readonly columns: readonly ['servicoId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamentos';
                    readonly columns: readonly ['clienteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamentos';
                    readonly columns: readonly ['barbeiroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamentos';
                    readonly columns: readonly ['servicoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'servicos';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly avaliacoes: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly agendamentoId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly clienteId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nota: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly comentario: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['agendamentoId'] }];
              indexes: readonly [
                {
                  readonly name: 'avaliacoes_clienteId_idx_7ae16308';
                  readonly prefix: 'avaliacoes_clienteId_idx';
                  readonly columns: readonly ['clienteId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'avaliacoes';
                    readonly columns: readonly ['agendamentoId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agendamentos';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'avaliacoes';
                    readonly columns: readonly ['clienteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly barbeiro_especialidades: {
              columns: {
                readonly barbeiroId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly especialidadeId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['barbeiroId', 'especialidadeId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'barbeiro_especialidades_barbeiroId_idx_9d9c2279';
                  readonly prefix: 'barbeiro_especialidades_barbeiroId_idx';
                  readonly columns: readonly ['barbeiroId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'barbeiro_especialidades_especialidadeId_idx_60ec3d64';
                  readonly prefix: 'barbeiro_especialidades_especialidadeId_idx';
                  readonly columns: readonly ['especialidadeId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'barbeiro_especialidades';
                    readonly columns: readonly ['barbeiroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'barbeiro_especialidades';
                    readonly columns: readonly ['especialidadeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'especialidades';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly disponibilidades: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly barbeiroId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly diaSemana: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly horaInicio: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly horaFim: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'disponibilidades_barbeiroId_idx_9d9c2279';
                  readonly prefix: 'disponibilidades_barbeiroId_idx';
                  readonly columns: readonly ['barbeiroId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'disponibilidades';
                    readonly columns: readonly ['barbeiroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly especialidades: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['nome'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly favoritos: {
              columns: {
                readonly clienteId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly barbeiroId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['clienteId', 'barbeiroId'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'favoritos_clienteId_idx_7ae16308';
                  readonly prefix: 'favoritos_clienteId_idx';
                  readonly columns: readonly ['clienteId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'favoritos';
                    readonly columns: readonly ['clienteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly fila_de_espera: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly clienteId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly barbeiroId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly dataDesejada: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'AGUARDANDO'>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'fila_de_espera_clienteId_idx_7ae16308';
                  readonly prefix: 'fila_de_espera_clienteId_idx';
                  readonly columns: readonly ['clienteId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'fila_de_espera';
                    readonly columns: readonly ['clienteId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuarios';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly servicos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly descricao: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly duracaoMin: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly preco: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly usuarios: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly senhaHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pontosFidelidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Role: {
              readonly kind: 'valueSet';
              readonly values: readonly ['CLIENTE', 'BARBEIRO', 'ADMINISTRADOR'];
            };
            readonly StatusAgendamento: {
              readonly kind: 'valueSet';
              readonly values: readonly ['CONFIRMADO', 'CANCELADO', 'CONCLUIDO'];
            };
            readonly StatusFila: {
              readonly kind: 'valueSet';
              readonly values: readonly ['AGUARDANDO', 'NOTIFICADO', 'CONFIRMADO', 'EXPIRADO'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly usuarios: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
    readonly servicos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Servico' };
    readonly especialidades: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Especialidade';
    };
    readonly barbeiro_especialidades: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'BarbeiroEspecialidade';
    };
    readonly disponibilidades: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Disponibilidade';
    };
    readonly agendamentos: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Agendamento';
    };
    readonly fila_de_espera: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FilaDeEspera';
    };
    readonly avaliacoes: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Avaliacao';
    };
    readonly favoritos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Favorito' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Agendamento: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly clienteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly barbeiroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly servicoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly data: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly horaInicio: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly horaFim: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly avaliacao: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Avaliacao';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['agendamentoId'];
                };
              };
              readonly barbeiro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['barbeiroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['clienteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly servico: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Servico';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['servicoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'agendamentos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clienteId: { readonly column: 'clienteId' };
                readonly barbeiroId: { readonly column: 'barbeiroId' };
                readonly servicoId: { readonly column: 'servicoId' };
                readonly data: { readonly column: 'data' };
                readonly horaInicio: { readonly column: 'horaInicio' };
                readonly horaFim: { readonly column: 'horaFim' };
                readonly status: { readonly column: 'status' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Avaliacao: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly agendamentoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly clienteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nota: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly comentario: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly agendamento: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['agendamentoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['clienteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'avaliacoes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly agendamentoId: { readonly column: 'agendamentoId' };
                readonly clienteId: { readonly column: 'clienteId' };
                readonly nota: { readonly column: 'nota' };
                readonly comentario: { readonly column: 'comentario' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly BarbeiroEspecialidade: {
            readonly fields: {
              readonly barbeiroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly especialidadeId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly barbeiro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['barbeiroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly especialidade: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Especialidade';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['especialidadeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'barbeiro_especialidades';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly barbeiroId: { readonly column: 'barbeiroId' };
                readonly especialidadeId: { readonly column: 'especialidadeId' };
              };
            };
          };
          readonly Disponibilidade: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly barbeiroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly diaSemana: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly horaInicio: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly horaFim: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly barbeiro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['barbeiroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'disponibilidades';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly barbeiroId: { readonly column: 'barbeiroId' };
                readonly diaSemana: { readonly column: 'diaSemana' };
                readonly horaInicio: { readonly column: 'horaInicio' };
                readonly horaFim: { readonly column: 'horaFim' };
              };
            };
          };
          readonly Especialidade: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly barbeiros: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BarbeiroEspecialidade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['especialidadeId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'especialidades';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
              };
            };
          };
          readonly Favorito: {
            readonly fields: {
              readonly clienteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly barbeiroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['clienteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'favoritos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly clienteId: { readonly column: 'clienteId' };
                readonly barbeiroId: { readonly column: 'barbeiroId' };
              };
            };
          };
          readonly FilaDeEspera: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly clienteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly barbeiroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly dataDesejada: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly cliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['clienteId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'fila_de_espera';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly clienteId: { readonly column: 'clienteId' };
                readonly barbeiroId: { readonly column: 'barbeiroId' };
                readonly dataDesejada: { readonly column: 'dataDesejada' };
                readonly status: { readonly column: 'status' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Servico: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly duracaoMin: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly preco: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 10; readonly scale: 2 };
                };
              };
            };
            readonly relations: {
              readonly agendamentos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['servicoId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'servicos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly descricao: { readonly column: 'descricao' };
                readonly duracaoMin: { readonly column: 'duracaoMin' };
                readonly preco: { readonly column: 'preco' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly senhaHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pontosFidelidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly agendamentosComoBarbeiro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['barbeiroId'];
                };
              };
              readonly agendamentosComoCliente: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Agendamento';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clienteId'];
                };
              };
              readonly avaliacoes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Avaliacao';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clienteId'];
                };
              };
              readonly disponibilidades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Disponibilidade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['barbeiroId'];
                };
              };
              readonly especialidades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'BarbeiroEspecialidade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['barbeiroId'];
                };
              };
              readonly favoritos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Favorito';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clienteId'];
                };
              };
              readonly filaDeEspera: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FilaDeEspera';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['clienteId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuarios';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly email: { readonly column: 'email' };
                readonly senhaHash: { readonly column: 'senhaHash' };
                readonly telefone: { readonly column: 'telefone' };
                readonly role: { readonly column: 'role' };
                readonly pontosFidelidade: { readonly column: 'pontosFidelidade' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
        };
        readonly enum: {
          readonly Role: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CLIENTE'; readonly value: 'CLIENTE' },
              { readonly name: 'BARBEIRO'; readonly value: 'BARBEIRO' },
              { readonly name: 'ADMINISTRADOR'; readonly value: 'ADMINISTRADOR' },
            ];
          };
          readonly StatusAgendamento: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'CONFIRMADO'; readonly value: 'CONFIRMADO' },
              { readonly name: 'CANCELADO'; readonly value: 'CANCELADO' },
              { readonly name: 'CONCLUIDO'; readonly value: 'CONCLUIDO' },
            ];
          };
          readonly StatusFila: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AGUARDANDO'; readonly value: 'AGUARDANDO' },
              { readonly name: 'NOTIFICADO'; readonly value: 'NOTIFICADO' },
              { readonly name: 'CONFIRMADO'; readonly value: 'CONFIRMADO' },
              { readonly name: 'EXPIRADO'; readonly value: 'EXPIRADO' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'agendamentos';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'avaliacoes';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'disponibilidades';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'especialidades';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'fila_de_espera';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'servicos';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'usuarios';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
